apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: tensorflow-trainer
  name: tensorflow-trainer
spec:
  template:
    metadata:
      name: tensorflow-trainer
    spec:
      volumes:
      - name: binaries
        hostPath:
          path: /usr/bin/
      - name: libraries
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      containers:
      - args:
        - --train
        image: ritazh/tf-server-gpu
        name: tensorflow-trainer
        env:
        - name: STORAGE_ACCOUNT_NAME
          value: mlgputraining
        - name: STORAGE_ACCOUNT_KEY
          value: pjP4k9BulPDqTzIL4ACNEsw7VgD5sZ4jVfhkPhzSK9Tqag3N/36EF5CX/EK9C8MrwRuZVd7Jwf4nv82Sc0mQ+A==
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/bin/
          name: binaries
        - mountPath: /usr/lib/x86_64-linux-gnu
          name: libraries
      restartPolicy: Never